USE PhoneBook
GO

IF OBJECT_ID('PHONE_NUMBERS') IS NOT NULL
	BEGIN
		ALTER TABLE PHONE_NUMBERS DROP CONSTRAINT FK_PHONE_NUMBERS_PERSON_ID
		ALTER TABLE PHONE_NUMBERS DROP CONSTRAINT FK_PHONE_NUMBERS_PHONE_TYPE_ID
		DROP TABLE PHONE_NUMBERS
	END
GO
IF OBJECT_ID('PERSONS') IS NOT NULL
	BEGIN
		ALTER TABLE PERSONS DROP CONSTRAINT FK_PERSONS_CITY_ID
		DROP TABLE PERSONS
	END
GO
DROP TABLE IF EXISTS dbo.PHONE_TYPES
GO
DROP TABLE IF EXISTS dbo.CITIES
GO

CREATE TABLE CITIES(
	ID int NOT NULL IDENTITY(1,1),
	UPDATE_COUNTER int NOT NULL DEFAULT 0,
	NAME nvarchar(128) NOT NULL,
	REGION nvarchar(128) NOT NULL,
	CONSTRAINT PK_CITIES_ID PRIMARY KEY(ID)
);
GO

CREATE TABLE PHONE_TYPES(
	ID int NOT NULL IDENTITY(1,1),
	UPDATE_COUNTER int NOT NULL DEFAULT 0,
	PHONE_TYPE nvarchar(128) NOT NULL,
	CONSTRAINT PK_PHONE_TYPES_ID PRIMARY KEY(ID) 
);
GO

CREATE TABLE PERSONS(
	ID int NOT NULL IDENTITY(1,1),
	UPDATE_COUNTER int NOT NULL DEFAULT 0,
	FIRST_NAME nvarchar(128) NOT NULL,
	MIDDLE_NAME nvarchar(128) NULL,
	LAST_NAME nvarchar(128) NOT NULL,
	EGN nvarchar(16) NOT NULL,
	CITY_ID int NOT NULL,
	ADDRESS nvarchar(256) NOT NULL,
	CONSTRAINT PK_PERSONS_ID PRIMARY KEY(ID),
	CONSTRAINT FK_PERSONS_CITY_ID FOREIGN KEY(CITY_ID) REFERENCES CITIES(ID)
);
GO

CREATE TABLE PHONE_NUMBERS(
	ID int NOT NULL IDENTITY(1,1),
	UPDATE_COUNTER int NOT NULL DEFAULT 0,
	PERSON_ID int NOT NULL,
	PHONE_TYPE_ID int NOT NULL,
	PHONE_NUMBER nvarchar(16) NOT NULL,
	CONSTRAINT PK_PHONE_NUMBERS_ID PRIMARY KEY(ID),
	CONSTRAINT FK_PHONE_NUMBERS_PERSON_ID FOREIGN KEY(PERSON_ID) REFERENCES PERSONS(ID),
	CONSTRAINT FK_PHONE_NUMBERS_PHONE_TYPE_ID FOREIGN KEY(PHONE_TYPE_ID) REFERENCES PHONE_TYPES(ID),
);
GO

CREATE UNIQUE INDEX UX_PERSONS_EGN
ON PERSONS(EGN)
GO

CREATE UNIQUE INDEX UX_PHONE_TYPES_PHONE_TYPE
ON PHONE_TYPES(PHONE_TYPE)
GO

CREATE UNIQUE INDEX UX_PHONE_NUMBERS_PHONE_NUMBER
ON PHONE_NUMBERS(PHONE_NUMBER)
GO

CREATE INDEX IX_PERSONS_CITY_ID
ON PERSONS(CITY_ID)
GO

CREATE INDEX IX_PHONE_NUMBERS_PERSON_ID
ON PHONE_NUMBERS(PERSON_ID)
GO

CREATE INDEX IX_PHONE_NUMBERS_PHONE_TYPE_ID
ON PHONE_NUMBERS(PHONE_TYPE_ID)
GO