USE PhoneBook
GO

DELETE FROM PHONE_NUMBERS
DBCC CHECKIDENT ('PHONE_NUMBERS', RESEED, 0)
GO
DELETE FROM PERSONS
DBCC CHECKIDENT ('PERSONS', RESEED, 0)
GO
GO
DELETE FROM PHONE_TYPES
DBCC CHECKIDENT ('PHONE_TYPES', RESEED, 0)

DELETE FROM CITIES
DBCC CHECKIDENT ('CITIES', RESEED, 0)
GO

INSERT INTO dbo.PHONE_TYPES
	(PHONE_TYPE)
VALUES
	('mobile'),
	('stationary')
GO

BEGIN TRY
	BEGIN TRANSACTION
		IF NOT EXISTS(SELECT * FROM CITIES
			WHERE NAME = 'Varna')
		BEGIN
			INSERT INTO dbo.CITIES
				(NAME, REGION)
			VALUES
				('Varna', 'Varna')
		END

		INSERT INTO dbo.PERSONS
			(FIRST_NAME, MIDDLE_NAME, LAST_NAME, EGN, ADDRESS, CITY_ID)
		VALUES
			('Grigor', 'Dimitrov', 'Grigorov', '7601178080', 'Bratq Miladinovi 81',
				(SELECT ID 
				 FROM CITIES
				 WHERE CITIES.NAME = 'Varna'))

		INSERT INTO dbo.PHONE_NUMBERS 
			(PHONE_NUMBER, PERSON_ID, PHONE_TYPE_ID)
		VALUES 
			('0877374137',
				(SELECT ID
				 FROM PERSONS
				 WHERE PERSONS.EGN = '7601178080'),
				(SELECT ID
				 FROM PHONE_TYPES
				 WHERE PHONE_TYPES.PHONE_TYPE = 'mobile'))

	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION
END CATCH

BEGIN TRY
	BEGIN TRANSACTION
		IF NOT EXISTS(SELECT * FROM CITIES
			WHERE NAME = 'Sofia')
		BEGIN
			INSERT INTO dbo.CITIES
				(NAME, REGION)
			VALUES
				('Sofia', 'Sofia')
		END

		INSERT INTO dbo.PERSONS
			(FIRST_NAME, MIDDLE_NAME, LAST_NAME, EGN, ADDRESS, CITY_ID)
		VALUES
			('Mihail', 'Aleksandrov', 'Aleksiev', '8912270550', 'Krasna Polqna 122',
			(SELECT ID 
			 FROM CITIES
			 WHERE CITIES.NAME = 'Sofia'))

		INSERT INTO dbo.PHONE_NUMBERS 
			(PHONE_NUMBER, PERSON_ID, PHONE_TYPE_ID)
		VALUES 
			('02372427',
			(SELECT ID
			 FROM PERSONS
			 WHERE PERSONS.EGN = '8912270550'),
			(SELECT ID
			 FROM PHONE_TYPES
			 WHERE PHONE_TYPES.PHONE_TYPE = 'stationary'))

	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION
END CATCH

BEGIN TRY
	BEGIN TRANSACTION
		IF NOT EXISTS(SELECT * FROM CITIES
			WHERE NAME = 'Varna')
		BEGIN
			INSERT INTO dbo.CITIES
				(NAME, REGION)
			VALUES
				('Varna', 'Varna')
		END

		INSERT INTO dbo.PERSONS
			(FIRST_NAME, MIDDLE_NAME, LAST_NAME, EGN, ADDRESS, CITY_ID)
		VALUES
			('Georgi', 'Todorov', 'Ivanov', '9105110744', 'Chereshovo Topche 25',
			(SELECT ID 
			 FROM CITIES
			 WHERE CITIES.NAME = 'Varna'))

		INSERT INTO dbo.PHONE_NUMBERS 
			(PHONE_NUMBER, PERSON_ID, PHONE_TYPE_ID)
		VALUES 
			('052213248',
			(SELECT ID
			 FROM PERSONS
			 WHERE PERSONS.EGN = '9105110744'),
			(SELECT ID
			 FROM PHONE_TYPES
			 WHERE PHONE_TYPES.PHONE_TYPE = 'stationary'))

	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION
END CATCH

BEGIN TRY
	BEGIN TRANSACTION
		IF NOT EXISTS(SELECT * FROM CITIES
			WHERE NAME = 'Pernik')
		BEGIN
			INSERT INTO dbo.CITIES
				(NAME, REGION)
			VALUES
				('Pernik', 'Sofia')
		END

		INSERT INTO dbo.PERSONS
			(FIRST_NAME, MIDDLE_NAME, LAST_NAME, EGN, ADDRESS, CITY_ID)
		VALUES
			('Spaska', 'Hristova', 'Kuzmanova', '9505110745', 'Svoboda 22',
			(SELECT ID 
			 FROM CITIES
			 WHERE CITIES.NAME = 'Pernik'))

	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION
END CATCH

BEGIN TRY
	BEGIN TRANSACTION
		IF NOT EXISTS(SELECT * FROM CITIES
			WHERE NAME = 'Beloslav')
		BEGIN
			INSERT INTO dbo.CITIES
				(NAME, REGION)
			VALUES
				('Beloslav', 'Varna')
		END

		INSERT INTO dbo.PERSONS
			(FIRST_NAME, MIDDLE_NAME, LAST_NAME, EGN, ADDRESS, CITY_ID)
		VALUES
			('Mihail', 'Tedosiev', 'Bozhkov', '9005110700', 'Baira 11',
			(SELECT ID 
			 FROM CITIES
			 WHERE CITIES.NAME = 'Beloslav'))

	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION
END CATCH

BEGIN TRY
	BEGIN TRANSACTION CHANGE_ADDRESS

		UPDATE PHONE_NUMBERS
			SET PHONE_NUMBER = '052372427'
			WHERE PERSON_ID = 
				(SELECT ID
				 FROM PERSONS
				 WHERE PERSONS.EGN = '8912270550')

		UPDATE PERSONS
			SET CITY_ID =
				(SELECT ID
				 FROM CITIES
				 WHERE CITIES.NAME = 'Varna')
			WHERE PERSONS.EGN = '8912270550'

		UPDATE PERSONS
			SET ADDRESS = 'Rila 12b'
			WHERE PERSONS.EGN = '8912270550'

	COMMIT TRANSACTION CHANGE_ADDRESS
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION CHANGE_ADDRESS
END CATCH
