USE PhoneBook

SELECT PERSONS.FIRST_NAME AS [first name], PERSONS.LAST_NAME AS [last name], CITIES.NAME AS [city]
FROM PERSONS
INNER JOIN CITIES 
	ON PERSONS.CITY_ID = CITIES.ID
GO

IF OBJECT_ID('VI_PHONE_NUMBERS_PHONE_TYPES_PERSONS', 'V') IS NOT NULL
	DROP VIEW VI_PHONE_NUMBERS_PHONE_TYPES_PERSONS
GO

CREATE VIEW VI_PHONE_NUMBERS_PHONE_TYPES_PERSONS
AS
	SELECT PHONE_NUMBERS.PHONE_NUMBER AS [phone number], PHONE_TYPES.PHONE_TYPE AS [phone type], PERSONS.FIRST_NAME AS [name]
	FROM PERSONS
	FULL OUTER JOIN PHONE_NUMBERS 
		ON PERSONS.ID = PHONE_NUMBERS.PERSON_ID
	LEFT JOIN PHONE_TYPES 
		ON PHONE_NUMBERS.PHONE_TYPE_ID = PHONE_TYPES.ID
GO

SELECT TOP (1000) [phone number],
	[phone type],
	[name]
FROM VI_PHONE_NUMBERS_PHONE_TYPES_PERSONS
GO

IF OBJECT_ID('VI_PERSONS_WITHOUT_PHONE_NUMBERS', 'V') IS NOT NULL
	DROP VIEW VI_PERSONS_WITHOUT_PHONE_NUMBERS
GO

CREATE VIEW VI_PERSONS_WITHOUT_PHONE_NUMBERS
AS
	SELECT PERSONS.FIRST_NAME AS [first name], PERSONS.LAST_NAME AS [last name], PERSONS.EGN AS EGN
	FROM PERSONS
	LEFT JOIN PHONE_NUMBERS
		ON PHONE_NUMBERS.PERSON_ID = PERSONS.ID
	WHERE PHONE_NUMBERS.PERSON_ID IS NULL
GO

SELECT TOP (50) [first name],
	[last name],
	[EGN]
FROM VI_PERSONS_WITHOUT_PHONE_NUMBERS
GO